<?php

/**
 *
 * @copyright  2010-2012 izend.org
 * @version    3
 * @link       http://www.izend.org
 */
?>
<div id="banner">
<?php echo $logo; ?>
<?php if (!empty($menu)): ?>
<?php echo $menu; ?>
<?php endif; ?>
<?php if (!empty($search)): ?>
<?php echo $search; ?>
<?php endif; ?>
<?php if (!empty($languages)): ?>
<?php echo $languages; ?>
<?php endif; ?>
<?php if (!empty($donate)): ?>
<?php echo $donate; ?>
<?php endif; ?>
</div>
