<?php

/**
 *
 * @copyright  2010-2026 izend.org
 * @version    27
 * @link       http://www.izend.org
 */
?>
<?php
foreach ($contents as $c) {
	switch($c['type']) {
		case 'text':
			$s = $c['text'];
			if ($s) {
				echo $s, PHP_EOL;
			}
			break;
		case 'file':
			$file_content = $c['file'];
			if ($file_content) {
				echo '<div class="file">', PHP_EOL, $file_content, PHP_EOL,'</div>', PHP_EOL;
			}
			break;
		case 'download':
			$file = $c['file'] ? htmlspecialchars($c['file'], ENT_COMPAT, 'UTF-8') : '';
			$download_url = $c['download_url'];
			echo '<div class="download">', PHP_EOL, '<a href="', $download_url, '" rel="nofollow">', $file, '</a>', PHP_EOL, '</div>', PHP_EOL;
			break;
		case 'infile':
			@include $c['infile'];
			break;
		case 'youtube':
			extract($c);	/* id width height center miniature title autoplay */
			$title= $title ? htmlspecialchars($title, ENT_COMPAT, 'UTF-8') : '';
			$class= $center ? 'youtube center' : 'youtube';
			$autoplay = $autoplay ? '1' : '0';
			$padding = round($height/$width, 4) * 100;
			$url = "https://www.youtube-nocookie.com/embed/$id?autoplay=$autoplay";
			$embed=<<<__MARK__
<div style="padding-bottom:{$padding}%;"><iframe allowfullscreen loading="lazy" src="$url" title="$title"></iframe></div>
__MARK__;
			if ($miniature) {
				$ytid = uniqid('id');
				echo '<div id="', $ytid, '" class="', $class, '" style="width:', $width, 'px;max-width:100%;"', ' title="', $title, '">', PHP_EOL;
				echo '<a href="https://www.youtube.com/watch?v=', $id, '"><span class="ytplay"></span><img src="', $base_path, $miniature, '" alt="" /></a>', PHP_EOL;
				echo '</div>', PHP_EOL;
				echo '<script>', PHP_EOL;
				echo 'var div=$("#', $ytid, '");', PHP_EOL;
				echo 'div.html(div.children().html());', PHP_EOL;
				echo 'div.children().click(function() { div.html(\'', $embed, '\'); })', PHP_EOL;
				echo '</script>', PHP_EOL;
			}
			else {
				echo '<div class="', $class, '" style="width:', $width, 'px;max-width:100%;">', PHP_EOL;
				echo $embed, PHP_EOL;
				echo '</div>', PHP_EOL;
			}
			break;
		default:
			break;
	}
}
?>
