<?php

/**
 *
 * @copyright  2010-2013 izend.org
 * @version    7
 * @link       http://www.izend.org
 */
?>
<?php require_once 'datefr.php'; ?>
<div id="homeblog">
<?php foreach ($blogsummary as $summary): extract($summary); ?>
<?php
$month = longmonth_fr($created);

$day = date('j', $created);
$year = date('Y', $created);
?>
<div class="blogsummary">
<?php if ($vote): ?>
<?php echo $vote; ?>
<?php endif; ?>
<div class="blogsummarytitle">
<div>
<p class="date"><?php if ($uri): ?><a href="/<?php echo $uri; ?>"><?php endif; ?><span class="day"><?php echo $day; ?></span> <span class="month"><?php echo $month; ?></span> <span class="year"><?php echo $year; ?></span><?php if ($uri): ?></a><?php endif; ?></p>
</div>
<div>
<h4><?php if ($uri): ?><a href="/<?php echo $uri; ?>"><?php endif; ?><?php echo htmlspecialchars($title, ENT_COMPAT, 'UTF-8'); ?><?php if ($uri): ?></a><?php endif; ?></h4>
<?php if ($author): ?>
<p class="author">par <?php if ($website): ?><a href="http://<?php echo $website; ?>" title="<?php echo $website; ?>"><?php endif; ?><?php echo $author; ?><?php if ($website): ?></a><?php endif; ?></p>
<?php endif; ?>
</div>
</div>
<div class="blogsummarycontent">
<?php echo $summary; ?>
</div>
<?php if ($cloud): ?>
<?php echo $cloud; ?>
<?php endif; ?>
<?php if ($uri): ?>
<p class="readmore"><a href="/<?php echo $uri; ?>">Lire la suite</a></p>
<?php endif; ?>
</div>
<?php endforeach; ?>
<?php if ($count > $pagesize): ?>
<?php
require_once 'pagerange.php';

$npages=ceil($count / $pagesize);
$pagenums=page_range($page, $npages, 2);
?>
<div class="pageselector">
<?php foreach ($pagenums as $p): ?>
<?php if ($p==$page): ?>
<span class="pagenumber currentpage"><?php echo $p; ?></span>
<?php else: ?>
<span class="pagenumber"><a href="?p=<?php echo $p; ?><?php if ($taglist): ?>&q=<?php echo urlencode(implode(' ', $taglist)); ?><?php endif; ?>"><?php echo $p; ?></a></span>
<?php endif; ?>
<?php endforeach; ?>
</div>
<?php endif; ?>
</div>
