<?php

/**
 *
 * @copyright  2013-2026 izend.org
 * @version    13
 * @link       http://www.izend.org
 */
?>
<?php $uri="$base_url/$request_path"; ?>
<a href="https://www.pinterest.com/pin/create/?url=<?php echo rawurlencode($uri); ?><?php if (!empty($pinit_image)): ?>&media=<?php echo rawurlencode("$base_url/$pinit_image"); ?><?php endif; ?><?php if (!empty($pinit_text)): ?>&description=<?php echo rawurlencode($pinit_text); ?><?php endif; ?>" target="_blank" rel="noopener noreferrer" title="Partager sur Pinterest">
<?php switch ($sharemode): ?>
<?php case 'awesome': ?>
<i class="fab fa-pinterest-p"></i>
<?php break; ?>
<?php case 'lite': ?>
<?php default: ?>
<span>Pinterest</span>
<?php break; ?>
<?php endswitch; ?>
</a>
