<?php

/**
 *
 * @copyright  2010-2012 izend.org
 * @version    4
 * @link       http://www.izend.org
 */
?>
<?php require_once 'dateen.php'; ?>
<div id="homeblog">
<?php foreach ($blogsummary as $summary): extract($summary); ?>
<?php
$month = longmonth_en($created);

$day = date('j', $created);
$year = date('Y', $created);
?>
<div class="blogsummary">
<div class="blogsummarytitle">
<div>
<p class="date"><a href="/<?php echo $uri; ?>"><span class="month"><?php echo $month; ?></span> <span class="day"><?php echo $day; ?></span><span class="comma">, </span><span class="year"><?php echo $year; ?></span></a></p>
</div>
<div>
<h4><a href="/<?php echo $uri; ?>"><?php echo $title; ?></a></h4>
<?php if($author): ?>
<p class="author">by <?php echo $author; ?></p>
<?php endif; ?>
</div>
</div>
<div class="blogsummarycontent">
<?php echo $summary; ?>
</div>
<?php if($cloud): ?>
<?php echo $cloud; ?>
<?php endif; ?>
<p class="readmore"><a href="/<?php echo $uri; ?>">Read more</a></p>
</div>
<?php endforeach; ?>
<?php if ($count > $pagesize): ?>
<?php
require_once 'pagerange.php';

$npages=ceil($count / $pagesize);
$pagenums=page_range($page, $npages, 2);
?>
<div class="pageselector">
<?php foreach ($pagenums as $p): ?>
<?php if ($p==$page): ?>
<span class="pagenumber currentpage"><?php echo $p; ?></span>
<?php else: ?>
<span class="pagenumber"><a href="?p=<?php echo $p; ?><?php if ($taglist): ?>&q=<?php echo urlencode(implode(' ', $taglist)); ?><?php endif; ?>"><?php echo $p; ?></a></span>
<?php endif; ?>
<?php endforeach; ?>
</div>
<?php endif; ?>
</div>
