<?php

/**
 *
 * @copyright  2019-2026 izend.org
 * @version    2
 * @link       http://www.izend.org
 */
?>
<a href="https://wa.me/?text=<?php echo rawurlencode("$base_url/$request_path"); ?>" target="_blank" rel="noopener noreferrer" title="Share on WhatsApp">
<?php switch ($sharemode): ?>
<?php case 'awesome': ?>
<i class="fab fa-whatsapp"></i>
<?php break; ?>
<?php case 'lite': ?>
<?php default: ?>
<span>WhatsApp</span>
<?php break; ?>
<?php endswitch; ?>
</a>
